### ISSUE TITLE
Renaming the robot doesn't work

### ISSUE THREAD

**Issue by elfro** [WaverleySoftware/robo-perception#56]
_**Branch:**_ `GH-47-add-missing-ros-events`
_**Mode:**_ simulator

_STR:_
1. Switch to the Settings tab
2. Edit robot's name by pressing any character on the keyboard or delete key

_Actual result:_ it's impossible to edit the name
_Expected result:_ it should be possible to rename the robot.

<img width="1509" alt="image" src="https://user-images.githubusercontent.com/8956849/213241246-ce58f9c6-07b0-42b5-9fd5-68bd37810e1d.png">

**Comment by sskorol** [comment]
Addressed in #54 PR
