### ISSUE TITLE
'Caps lock' state collision 

### ISSUE THREAD

**Issue by elfro** [WaverleySoftware/robo-perception#74]
Need to investigate how we can detect the activated / deactivated Caps lock mode on the keyboard and sync states when a user returns to the application tab.
_STR:_
1. Open an app in the browser
2. Enable Caps lock mode on the keyboard
3. Switch to any other application to make our robo app inactive
4. Press Caps lock on the keyboard
5. Return to the browser tab with our app
6. Press navigation key on the keyboard

_Actual result:_ the Caps lock mode is still highlighted on the UI keyboard, but it's already disabled on the real keyboard. As a result, when the user presses any mapped key on the keyboard, there is a collision in the movements.
_Expected result:_ the caps lock UI state should be sync with the current state on the keyboard when a user returns to the application tab and press the mapped key on the keyboard.

**Comment by alex-waverley** [comment]
I'd like to add more details to current issue related to switching between tabs or another case when tab loses its focus: if user clicks on virtual keyboard `shift` or `capslock` buttons, goes to another tab and then goes back - they will see correct layout (shift or capslock), but needed buttons won't be highlighted.
